### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by SionDarius** [Stary2001/InputClient-SDL#2]
I downloaded this and I run make ./input 192.168.x.xxx (not telling my ip) and I get this error:
Checking current platform
Current platform is Linux. OK...
gcc -c src/settings.c -o obj/settings.o -g -I/usr/include/SDL2
\src/settings.c:4:17: fatal error: SDL.h: No such file or directory
compilation terminated.
Makefile:24: recipe for target 'obj/settings.o' failed
make: *** [obj/settings.o] Error 1

There is no SDL.h file in the src folder.

**Comment by Stary2001** [comment]
That error means you need to install the SDL2 development files from your distribution's package manager.
Also, this client does not work with the NTR-mode of InputRedirection as I have not (re)implemented the NTR debugger protocol.
