### ISSUE TITLE
macOS Sierra Black Screen

### ISSUE THREAD

**Issue by andrewLarsson** [Stary2001/InputClient-SDL#3]
On macOS Sierra (10.12.5 on MacBook Pro Retina, 15-inch, Late 2013, NVIDIA GeForce GT 750M), all I get is a black window after running `./input <my-3DS-IP>`. Made sure to install SDL2 and SDL2-TTF and the required font. It recognizes my IP and detects my joystick just fine and doesn't produce any errors. I can provide some screenshots if you need.

**Comment by matheusfaustino** [comment]
Hello @andrewLarsson, I'm using macOS El Capitan and I get black screen too. But when I press F1, F2 and F3 it shows the configs and you can change them navigating with the arrows and pressing enter.

I hope answering your question.

**Comment by andrewLarsson** [comment]
@matheusfaustino Thank you for this! It works like a charm!
